### ISSUE TITLE
Código base del cliente de plan de adquisiciones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_cliente#1]
Se requiere realizar una copia de un cliente ya existente en la organización y subir su código con las 3 ramas principales  este repositorio, para ello se ha de tener en cuenta lo siguiente:

- [x] se debe de informar de cual cliente se realizara la copia según la estructura del proyecto (ya qe entre varios proyectos existen variaciones"

- [x] se deben de mantener en este repositorio las ramas principales , tal como están definidas en los lineamientos 
      ***primero se debe de subir la rama master*** 

- [x] realizar limpieza de código de tal manera que no se mantenga código del aplicativo del cual se hizo la copia , con la finalidad de no mantener código basura.

**Comment by ManuelMurillo** [comment]
Teniendo en cuenta los siguientes repositorios:

- https://github.com/udistrital/arka_cliente

- https://github.com/udistrital/presupuesto_cliente

Se toman en cuenta los siguientes aspectos calificandolos de 1 a 5:

| Aspecto | arka_cliente | presupuesto_cliente | Observaciones |
| ------------- | ------------- | ------------- | ------------- |
| Arquitectura | 4  | 4 | Las dos aplicaciones ofrecen arquitecturas similares, sus diferencias son muy pequeñas en comparacion |
| Librerias | 2  | 4 | Las librerias de Presupuesto trabajan con angular 8, mientras que Las librerias de Arka Trabajan con Angular 7 |
| Estetica | 4  | 4 | Arka tiene ajustados mas detalles visuales que Presupuesto, como en el menu principal, carga de inicio, sin embargo Presupuesto tiene configurado el tema necesario de Kronos |
| Rendimiento | 3  | 3.5 | En general el rendimiento es similar, sin embargo hay aspectos que en general se pueden mejorar, como el lazy loading, renderizacion de vistas entre otros |
| Limpieza | 4  | 3 | Arka tiene menos codigo basura en comparacion con Presupuesto |
| **Total** | **17**  | **18.5** |  |

Conclusion: Se Seleccionara como cliente base el cliente de **Presupuesto.** El argumento mas fuerte por el cual se selecciona es por la implementacion de angular 8, el cual ofrece mas funcionalidades que angular 7. Adicional a esto es necesario realizar unos ligeros ajustes para la arquitectura, y poder incluir ciertas caracteristicas adicionales como el uso del patron Redux, reduccion de codigo basura y ligeros ajustes en los modulos.
