### ISSUE TITLE
creación del menú para la aplicación de plan de adquicisiones en el aplicativo de configuración

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_cliente#12]
se requiere en el aplicativo de configuracion realizar el respectivo registro del menu para el aplicativo de plan de adquisiciones

**Comment by ManuelMurillo** [comment]
Inicialmente, para el plan de adquisiciones es necesario crear el primer item del menu:

Nombre: Gestion de Lineamientos
Ruta:      http://localhost:4200/#/pages/plan-adquisiciones/lineamientos (pagina local)

Para los modulos de Metas y Actividades, no se coloca la ruta directa debido a que estos dependen de la informacion del moduloo de Lineamientos. Para acceder a metas se usa Lineamientos, y para acceder a Actividades se usa Metas

**Comment by BOTOOM** [comment]
la opcion del menu fue creada y responde bajo la siguiente peticion

`https://autenticacion.portaloas.udistrital.edu.co/apioas/configuracion_crud_api/v1/menu_opcion_padre/ArbolMenus/CONTRATISTA,SUPERVISOR,ADMIN_NECESIDADES,ADMIN_PRESUPUESTO,ADMIN_CONTABILIDAD/plan_adquicisiones`

en la peticion del sistema como esta actualmente, despues del ultimo `/` dice **`presupuesto_kronos`** , debe de cambiarse a **`plan_adquicisiones`**

**Comment by ManuelMurillo** [comment]
de ajusta el menu en el commit https://github.com/udistrital/plan_adquisiciones_cliente/pull/19/commits/3c94f8634fced780bc06dfc95e9a642657412233
