### ISSUE TITLE
crear vista previa para plan de adquisiciones (tabla)

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_cliente#14]
tabla donde están todos los planes de adquisiciones , luego de ello para crear uno nuevo pida los datos básicos del plan y luego de ello si se proceda a su creación

**se permite el crear datos de pruebas en el entorno montado con docker para realizar pruebas**

**Comment by ManuelMurillo** [comment]
en el archivo re vistas relacionado en el issue #2 se agrega el mockup correspondiente a esta vista
![Mockup Plan de Adquisiciones Lineamientos y Metas-Gestion Planes de Adquisiciones 1920x1080 16_9](https://user-images.githubusercontent.com/29108085/99727039-6517af00-2a85-11eb-8d6e-6a26a56af900.png)
