### ISSUE TITLE
creación de mockups web del cliente de plan de adquisiciones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_cliente#2]
se requiere crear mockups web para plan de adquisiciones con el fin de definir detalles del desarrollo

**Comment by ManuelMurillo** [comment]
En el siguiente archivo se encuentran los mockups para el plan de adquisicion:

https://drive.google.com/file/d/1bOTaw5f82IS3ByBgniptTAvfHx_STqt-/view?usp=sharing

**Comment by ManuelMurillo** [comment]
Lineamientos:
![Mockup Plan de Adquisiciones Lineamientos y Metas-Lineamientos 16_10 1920x1200](https://user-images.githubusercontent.com/29108085/96328379-f53a8280-1007-11eb-9591-bafd8e7708b0.png)

Metas:
![Mockup Plan de Adquisiciones Lineamientos y Metas-Metas 16_10 1920x1200](https://user-images.githubusercontent.com/29108085/96328381-fbc8fa00-1007-11eb-82f8-3b79404dccd1.png)

Actividades: 
![Mockup Plan de Adquisiciones Lineamientos y Metas-Actividades 16_10 1920x1200](https://user-images.githubusercontent.com/29108085/96328385-04213500-1008-11eb-86eb-fc468904aa95.png)

**Comment by ManuelMurillo** [comment]
Creacion Rubro Funcionamiento
![Mockup Plan de Adquisiciones Lineamientos y Metas-Creacion Plan Funcionamiento 16_10 1920x1200](https://user-images.githubusercontent.com/29108085/96678231-eb31c000-1336-11eb-9b3d-e910e5263307.png)

**Comment by ManuelMurillo** [comment]
Tabla Rubro Funcionamiento
![Mockup Plan de Adquisiciones Lineamientos y Metas-Funcionamiento Plan 16_10 1920x1200](https://user-images.githubusercontent.com/29108085/96678273-03a1da80-1337-11eb-96c7-4f6ebe297f1e.png)

**Comment by ManuelMurillo** [comment]
Creacion Rubro Inversion
![Mockup Plan de Adquisiciones Lineamientos y Metas-Creacion Plan Inversion 16_10 1920x1200](https://user-images.githubusercontent.com/29108085/96678339-1f0ce580-1337-11eb-8df0-2a3320b96699.png)

**Comment by ManuelMurillo** [comment]
Mostrar Plan de Adquisiciones
![Mockup Plan de Adquisiciones Lineamientos y Metas-Mostrar Plan 16_10 1920x1200](https://user-images.githubusercontent.com/29108085/96678391-33e97900-1337-11eb-8a10-8caa10bcbbaf.png)

**Comment by ManuelMurillo** [comment]
Edicion Rubro Inversion
![Mockup Plan de Adquisiciones Lineamientos y Metas-Edicion Inversion 16_10 1920x1200](https://user-images.githubusercontent.com/29108085/96678436-4c599380-1337-11eb-8956-e99d31b047ae.png)

**Comment by ManuelMurillo** [comment]
Se Agregan las vistas faltantes para la creacion y edicion para el plan de adquisiciones, los cambios se encuentran en el mismo archivo de vistas presentado inicialmente
