### ISSUE TITLE
conectarse con el back para poder consultar cada versión del plan de adquisiciones de manera individual

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_cliente#41]
en continuación al issue #35 se requiere que en la acción de la tabla se pueda consultar la versión del plan de adquisiciones y poderla mostrar a nivel de consulta y no de edición

**Comment by ManuelMurillo** [comment]
Al hacer la tarea he encontrado algunos ajustes que es necesario realizar en el objeto de publicacion, debido a que hay datos que puede que hacen falta para que el cliente requiera de realizar muchas peticiones de forma continua:

- [ ] si se pudiera colocar la fuente de recurso estaria bien, debido a que esta debe estar relacionada
- [ ] en el rubro falta el nombre para no realizar ninguna peticion adicional
- [ ] para la meta si se puede montar el objeto completo estaria bien, si no revisar la funcion RelatedSel del CRUD debido a que no trae todos los datos
- [ ] para el producto es necesario Codigo y Nombre para visualizar
- [ ] para el responsable es necesario el nombre
- [ ] para los elementos de arka se puede agregar la descripcion
- [ ] para las fuentes de financiamiento se requiere el nombre de la fuente
- [ ] no se esta guardando el area funcional en la publicacion
- [ ] en ocasiones al parecer la transaccion no se realiza completamente lo cual monta datos nulos

**Comment by BOTOOM** [comment]
se tendran esos datos en cuenta
