### ISSUE TITLE
revisar el cliente en busca de bugs y listarlos

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_cliente#42]
se requiere realizar pruebas de funcionalidad al cliente en busca de posible bugs o fallos de la aplicación y listarlos en una tabla en el presente issue

**Comment by ManuelMurillo** [comment]
| Descripcion | Ajustado |
| --- | --- |
| no se muestra el dato en select con virtual scrolling |  |
| en la edicion de la actividad el campo se deja cambiar y no deberia hacerlo |  |
|  |  |
|  |  |
