### ISSUE TITLE
cambiar nombre de los interface de configuraciones y eliminar datos de prueba ya no usados

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_cliente#43]
se requiere revisar los archivos de interface en los cuales se exportan interface tando de configuracion para las tablas y de datos de prueba.

se requiere:
- [x] eliminar todos los datos de prueba que ya no se usen.
- [x] cambiar el nombre de las configuraciones a un nombre mas explicito, ya no es valido decir que son de prueba ya que los módulos ya están listos, al cambiarlos en los archivos de interface es necesario cambiarlos donde son importados (se recomienda usar el buscador de visual studio code)

**Comment by ManuelMurillo** [comment]
Para el Modulo de prueba (src/app/pages/primer-modulo) es necesario mantener las configuraciones y los datos de prueba, debido a que en este modulo se prueban las configuraciones de la tabla antes de ser agregadas al desarrollo
