### ISSUE TITLE
realizar corrección de bugs del cliente de plan de adquisiciones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_cliente#51]

**Comment by ManuelMurillo** [comment]
Segun el issue #42 se listan los bugs encontrados:

| Descripcion | Ajustado |
| --- | --- |
| No se muestra el dato en select con virtual scrolling |  |
| En la edicion de la actividad el campo se deja cambiar y no deberia hacerlo |  |
| No se muestra el codigo de la actividad en la tabla de actividades en el formulario del plan |  |
| Las metas de la ficha estadistica ya asociadas no deberian mostrarse al crear una ficha nueva |  |
| El formulario del renglon del plan no se ajusta luego de que el plan ya esta publicado |  |
| Las leyendas de algunos componentes no se ajustan el espacio asociado |  |
| No hay forma de volver en los lineamientos, metas y actividades |  |
| Algunos ids estan repetidos en los formularios |  |
| Error en la paleta de colores en despliegue |  |
| En caso de error volver a las rutas iniciales |  |
