### ISSUE TITLE
realizar listado de ajuste a aplicar para suplir los cambios propuestos en la socializacion

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_cliente#61]
con base a la socializacion del plan de adquisiciones #54 se requiere presentar propuestas de los cambios a realizar

**Comment by ManuelMurillo** [comment]
Segun la lista de ajustes relacionada en el issue #54 los siguientes ajustes se pueden arreglar directamente en el cliente:

- [ ] actividades se puede acceder por usuario de dependencias

- [ ] la fecha estimada no puede superar el año

- [ ] código de arca debe de decir código unspsc

- [ ] se debe de revisar ya que en el plan de adquisiciones parece que no se consulta el ultimo nivel del catalogo de colombia compra eficiente, se ha de validar con el penúltimo nivel

- [ ] controlar error de no selección de área funcional

- [ ] el valor de la actividad distribuido a una fuente ni pyede superar el valor que ya se le habia asignado previamente la fuente

- [ ] validar el no poder seleccionar la misma actividad ya selecionada previamente

Para los siguientes ajustes es necesario una revision de modelo:

- [ ] una meta puede tener varios rubros

- [ ] una actividad puede tener muchos rubos ,pero solo se puede seleccionar los que se escogieron anteriormente en la meta

Para este ajuste es necesario solicitar la adicion del registro:

- [ ] añadir registro de dependencia solicitante a oikos

**Comment by ManuelMurillo** [comment]
En la reunion realizada el 26/01/2021, con la Ingeniera Diana Guayara, se realizaron ciertas preguntas y ciertas observaciones con respecto a la socializacion del plan de adquisiciones y los ajustes solicitados. se tuvo en cuenta lo siguientes aspectos:

- [ ] Pueden haber varios productos en el registro de inversion del renglon del plan de adquisiciones
- [ ] Pueden haber varias metas en el registro de inversion del renglon del plan de adquisiciones
- [ ] Se deben ajustar los registros del renglon para en caso de funcionamiento para mostrarlos segun el mockup
- [ ] Se debe revisar el uso de lineamientos debido a la confusion entre estas Metas (Inversion, asociadas a los rubros de inversion) y las metas del plan estrategico (Funcionamiento)

**Comment by ManuelMurillo** [comment]
En la reunion del 28/01/2021 en la cual se iban a solventar estas incognitas, se aplazo para el 01/02/2021

**Comment by ManuelMurillo** [comment]
Estas son algunas tareas tentativas para realizar los ajustes solicitados relacionados por seccion:

**CRUD**

- Agregar Tabla para asociar Metas
- Agregar Tabla para asociar Productos
- Agregar ajustes para registro Funcionamiento

**MID**

- Ajustar Registro del Renglon para agregar Metas y Productos
- Ajustar Registro para Funcionamiento (si no esta la funcionalidad)
- Ajustar Objeto de Publicacion

**Cliente**

- Agregar Componente para Metas
- Agregar Componente para Productos
- Ajustar Registro del Renglon

Dependiendo de las observaciones propuestas es posible que estas tareas tentativas puedan cambiar
