### ISSUE TITLE
revisar el uso de lineamientos para plan de adquisiciones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_cliente#63]
ya que hay dudas sobre el uso de lineamientos o u implementación para el plan de adquisiciones, se quiere realizar la respectiva reunión y definir este tema

**Comment by ManuelMurillo** [comment]
Segun La reunion del 01/02/2021 y teniendo en cuenta las instrucciones de los presentes, la seccion de lineamientos se va a ajustar para no usarse debido a la confusion generada con la documentacion y el desarrollo.
