### ISSUE TITLE
usar version web de pdfmaker par realizar plantilla de plan de adquicisiones

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/plan_adquisiciones_cliente#65]
con la finalidad de poder proporcionar una versión en pdf del plan de adquisiciones se requiere revisar la librería pdfmaker , usando su editor web , realizar la plantilla de como quedaría la versión pdf del plan de adquisiciones. para finalizar la tarea se requiere: 

- [x] dar muestra el pdf resultante.
- [x] subir al presente issue el código para armar la plantilla

**Comment by ManuelMurillo** [comment]
Esta es la primera version de la publicacion del plan de adquisiciones teniendo en cuenta la informacion de la parte grafica del plan de adquisiciones:

Primera Version:

[Plantilla Plan de Adquisiciones.pdf](https://github.com/udistrital/plan_adquisiciones_cliente/files/5908404/Plantilla.Plan.de.Adquisiciones.pdf)

Objeto Plantilla:

https://drive.google.com/file/d/1zZCWiK_9NkR6t8Knlm6kQBijjX5pOeaS/view?usp=sharing

**Comment by ManuelMurillo** [comment]
se presenta la plantilla final para la publicacion del plan de adquisiciones:

[file (16).pdf](https://github.com/udistrital/plan_adquisiciones_cliente/files/6092587/file.16.pdf)
