### ISSUE TITLE
Cuando se actualizan rubros de funcionamiento no se encuentra el plan

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/plan_adquisiciones_cliente#95]
## Consideraciones
- De la Revisión/problema mencionado en el [Daily del 30 de Diciembre]():
  - Pareciera que al momento de editar un rubro (con el fin de preparar una nueva versión, antes de) del plan de adquisiciones a los ID se les están sumando una constante

## Tareas
(TODO: Por Definir)

**Comment by brayanpasa99** [comment]
Se encuentra un error en el funcionamiento dados los cambios producidos en Movimientos CRUD para pasar a producción. Se re abre el issue

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
